from PyQt5.QtCore import Qt

ddd = { Qt.Key_Z : 60, 
        Qt.Key_S : 61, 
        Qt.Key_X : 62, 
        Qt.Key_D : 63, 
        Qt.Key_C : 64, 
        Qt.Key_V : 65, 
        Qt.Key_G : 66, 
        Qt.Key_B : 67, 
        Qt.Key_H : 68, 
        Qt.Key_N : 69, 
        Qt.Key_J : 70, 
        Qt.Key_M : 71,  
        Qt.Key_Q : 72, 
        Qt.Key_2 : 73, 
        Qt.Key_W : 74, 
        Qt.Key_3 : 75, 
        Qt.Key_E : 76, 
        Qt.Key_R : 77, 
        Qt.Key_5 : 78,
        Qt.Key_T : 79, 
        Qt.Key_6 : 80, 
        Qt.Key_Y : 81, 
        Qt.Key_7 : 82, 
        Qt.Key_U : 83, 
        Qt.Key_I : 84 ,
        Qt.Key_9 : 85 ,
        Qt.Key_O : 86 ,
        Qt.Key_0 : 87 ,
        Qt.Key_P : 88 ,
        Qt.Key_BracketLeft : 89,
        Qt.Key_BracketRight : 90
        }